In [1]:
import numpy as np
import h5py

### Check Carlsen Dataset

In [3]:
filename = "/data/chess0.h5"
h5 = h5py.File(filename,'r')

In [5]:
h5.keys()

<KeysViewHDF5 ['boards', 'evaluations', 'moves', 'turns']>

In [24]:
h5["boards"][100]

array([[13, 15,  0, 18, 19, 17, 15, 13],
       [11, 11, 11,  0, 11, 11, 11, 11],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 11,  0, 16,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  1,  0],
       [ 1,  7,  1,  1,  1,  1,  0,  1],
       [ 3,  5,  0,  8,  9,  6,  5,  3]])

In [31]:
h5["evaluations"][:100]

array([ -17,  -16,  -26,  -34,   18,   24,  -16,   26,   14,   24,  -86,
        -27,   21, -131,   -6,  -49,   -3,  -74,  -61,   27,  -30,  -26,
        -13,  -97,  -81,  -55,  -17,   17,  -18,   -1,   -8,  -14,  -33,
        -23,  -21,  -32,  -11,  -38,  -87,  -18, -115,  -58,  -92,  -86,
        -61,  -46,  -20,  -30, -118, -131,  -60,  -61, -249,  -70, -125,
        -85,  -99, -140,   -1,    0,  -26,  -71,  -11,  -26, -387, -427,
        -49,  -53,  -15,  -92,  -11,  -26,  -27,  -65,  -24,  -37,  -13,
        -40,  -70,  -33,  -18,  -30,  -33,    6,    0, -507,  -70,  -18,
       -126,  -59,   -6,  -15,  -90,  -38,  -17,  -19,  -12, -153, -117,
        -41])

In [30]:
h5["moves"][:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [29]:
h5["turns"][:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Opening 2023 World

In [1]:
from utils.dataset import PGNDataset

In [2]:
data = PGNDataset("/root/new-data/WorldChamp2023.pgn.zip","/root/new-data-processed/")

WorldChamp2023.pgn
__MACOSX/._WorldChamp2023.pgn
b'[Event "WCh 2023"]\n'
b'[Site "Astana KAZ"]\n'
b'[Date "2023.04.09"]\n'
b'[Round "1.1"]\n'
b'[White "Nepomniachtchi,I"]\n'
b'[Black "Ding Liren"]\n'
b'[Result "1/2-1/2"]\n'
b'[WhiteElo "2795"]\n'
b'[BlackElo "2788"]\n'
b'[ECO "C85"]\n'
b'\n'
b'1.e4 e5 2.Nf3 Nc6 3.Bb5 a6 4.Ba4 Nf6 5.O-O Be7 6.Bxc6 dxc6 7.Re1 Nd7 8.d4 exd4\n'
b'9.Qxd4 O-O 10.Bf4 Nc5 11.Qe3 Bg4 12.Nd4 Qd7 13.Nc3 Rad8 14.Nf5 Ne6 15.Nxe7+ Qxe7\n'
b'16.Bg3 Bh5 17.f3 f6 18.h3 h6 19.Kh2 Bf7 20.Rad1 b6 21.a3 a5 22.Ne2 Rxd1 23.Rxd1 Rd8\n'
b'24.Rd3 c5 25.Qd2 c6 26.Rxd8+ Nxd8 27.Qf4 b5 28.Qb8 Kh7 29.Bd6 Qd7 30.Ng3 Ne6\n'
b'31.f4 h5 32.c3 c4 33.h4 Qd8 34.Qb7 Be8 35.Nf5 Qd7 36.Qb8 Qd8 37.Qxd8 Nxd8\n'
b'38.Nd4 Nb7 39.e5 Kg8 40.Kg3 Bd7 41.Bc7 Nc5 42.Bxa5 Kf7 43.Bb4 Nd3 44.e6+ Bxe6\n'
b'45.Nxc6 Bd7 46.Nd4 Nxb2 47.Kf3 Nd3 48.g3 Nc1 49.Ke3  1/2-1/2\n'
b'\n'
b'[Event "WCh 2023"]\n'
b'[Site "Astana KAZ"]\n'
b'[Date "2023.04.10"]\n'
b'[Round "2.1"]\n'
b'[White "Ding Liren"]\n'
b'[Black "Nep

In [3]:
data[0]

('[Event "WCh 2023"]\n[Site "Astana KAZ"]\n[Date "2023.04.09"]\n[Round "1.1"]\n[White "Nepomniachtchi,I"]\n[Black "Ding Liren"]\n[Result "1/2-1/2"]\n[WhiteElo "2795"]\n[BlackElo "2788"]\n[ECO "C85"]',
 '1.e4 e5 2.Nf3 Nc6 3.Bb5 a6 4.Ba4 Nf6 5.O-O Be7 6.Bxc6 dxc6 7.Re1 Nd7 8.d4 exd4 9.Qxd4 O-O 10.Bf4 Nc5 11.Qe3 Bg4 12.Nd4 Qd7 13.Nc3 Rad8 14.Nf5 Ne6 15.Nxe7+ Qxe7 16.Bg3 Bh5 17.f3 f6 18.h3 h6 19.Kh2 Bf7 20.Rad1 b6 21.a3 a5 22.Ne2 Rxd1 23.Rxd1 Rd8 24.Rd3 c5 25.Qd2 c6 26.Rxd8+ Nxd8 27.Qf4 b5 28.Qb8 Kh7 29.Bd6 Qd7 30.Ng3 Ne6 31.f4 h5 32.c3 c4 33.h4 Qd8 34.Qb7 Be8 35.Nf5 Qd7 36.Qb8 Qd8 37.Qxd8 Nxd8 38.Nd4 Nb7 39.e5 Kg8 40.Kg3 Bd7 41.Bc7 Nc5 42.Bxa5 Kf7 43.Bb4 Nd3 44.e6+ Bxe6 45.Nxc6 Bd7 46.Nd4 Nxb2 47.Kf3 Nd3 48.g3 Nc1 49.Ke3  1/2-1/2')

### Rob Data

In [4]:
import torch

In [5]:
data = torch.load("/root/rob/chess-hackathon/general_dataset.pt")

In [9]:
data[100]

(tensor(0),
 tensor(0),
 tensor([[13,  0, 16, 19, 14,  0,  0,  0],
         [11,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0, 11,  0,  0,  0,  0, 11],
         [ 0,  0,  0,  0, 17,  0, 11,  0],
         [ 0,  0,  0, 11,  0,  0,  0,  0],
         [ 0,  0,  0,  1,  0,  1,  0,  0],
         [ 1,  1,  1,  7,  0,  0,  0,  1],
         [ 3,  0,  0,  9,  0,  0,  0,  3]]),
 tensor(-456))

In [10]:
len(data)

304856